### ISSUE TITLE
static text

### ISSUE THREAD

**Issue by workspace-cs** [DoganOnur/live_expectancy#4]
https://github.com/DoganOnur/live_expectancy/blob/d2d3e9a192474b50dba10fb7b78e21900fa68973/lib/input_page.dart#L27

Textler toplanmalı. Bu sekilde dil degisikligi yapmak istersen tek yerden yontebilrisin. Ayrıca dinamikligi artırır.

**Comment by DoganOnur** [comment]
Tek bir yerden toplanmayı diyorsun galiba update hepsini düzenleme yapacağım. Teşekkürler :)
