### ISSUE TITLE
tema uzerinden widgetlera stil vermek

### ISSUE THREAD

**Issue by workspace-cs** [DoganOnur/live_expectancy#6]
https://github.com/DoganOnur/live_expectancy/blob/d2d3e9a192474b50dba10fb7b78e21900fa68973/lib/input_page.dart#L160

Rengi vs direkt olarak ayarlarsan tema degiskliginde renk aynı kalir. Ozelliestirmeleri tema uzerinden okumalısın.

**Comment by DoganOnur** [comment]
Evet Theme ile yapmak istedim sonra property üzerinden görmek sürekli değiştirmek için yaptım. Ama dediğin daha mantıklı ve düzenli kod olur. Update committe bunu yaparım.Teşekkürler
